### ISSUE TITLE
Make it possible to Indent Code Blocks

### ISSUE THREAD

**Issue by zicklag** [Canop/termimad#11]
Is there a way to indent code blocks? I see that you can set the alignment to left, center, or right, but can I add four spaces indent to a left-aligned code block?

**Comment by Canop** [comment]
There's no way currently. I'll take this question as a request for addition.

**Comment by andrewtc** [comment]
If you are looking for someone to take this on, I may be willing to provide dev support. I was wanting this feature the other day for a personal project of mine.

**Comment by Canop** [comment]
@andrewtc @zicklag tests of https://github.com/Canop/termimad/pull/58 would be welcome

**Comment by zicklag** [comment]
@Canop tested and it looks good! ✅

**Comment by Canop** [comment]
Thanks. I'll merge it, then.

The fact the wrapping functions takes the skin as parameter will enable a few other changes.

**Comment by Canop** [comment]
Available in 0.27.0
