### ISSUE TITLE
Missing characters from text when wrapped in a MadView

### ISSUE THREAD

**Issue by abusch** [Canop/termimad#17]
I ran the `scrollable` example from termimad 0.8.17 and noticed there are a few characters missing (see screenshot). For instance, the `w` from `wrapping` on line 7 and the `b` from `but parsing is cheap` on line 32.

It seems like it happens when the beginning of a bold or italic section gets wrapped to the beginning of the line maybe?

![2020-04-10-180358_2657x2752_scrot](https://user-images.githubusercontent.com/506344/78974850-3d0eb780-7b56-11ea-8eb3-79766b3c0288.png)

**Comment by Canop** [comment]
Confirmed.
Thanks for the report.
