### ISSUE TITLE
wrapping bulleted text -- bug?

### ISSUE THREAD

**Issue by bradwood** [Canop/termimad#21]
Hi,

I have this when I wrap bulleted text:

```
- [x] gfsdsdfsdfsdfsdf sdf sd fsd fsdf 
sdfsdf
```
Can the 2nd+ lines also be made to be as indented as the first, like so:
```
- [x] gfsdsdfsdfsdfsdf sdf sd fsd fsdf 
      sdfsdf
```

thanks!

**Comment by Canop** [comment]
Not really a bug, this was by design (space is often lacking in terminals). But it could be changed, maybe with a skin setting. I note the request.

**Comment by bradwood** [comment]
Ok. I guess this is a personal preference thing, but it definitely looks like a bug to me. Most HTML markdown renderers seem do indent the 2nd+ lines that i can see...

* example example example example example example example example example example example example example example example example example example example example example example example example example example example example example example example example example example example example example example

**Comment by wullxz** [comment]
I also noticed this. We're generating help for one of our projects in markdown and use the MD in our wiki (gitlab wiki) and - using termimad - on the shell. I don't think the indentation is a problem on the shell.  
It would be nice if it was configurable at least. Any chance we could get config options for toggling that behaviour?

**Comment by Canop** [comment]
> Any chance we could get config options for toggling that behaviour?

Yes. This is mostly a matter of me managing to find some free time.

**Comment by Canop** [comment]
(managed to find some free time... just not fast)
