### ISSUE TITLE
Termimad Parses some random text when used with TUI

### ISSUE THREAD

**Issue by ahmedsaheed** [Canop/termimad#32]
I am trying to  parse markdown input with termimad in a tui widget but  i get an output like this `[48;5;235m[38;5;249mhi[49m[39m` when i  type a string `hi` with two single quote (``) around it.

To reproduce 

```rs
    let input = Paragraph::new(termimad::MadSkin::default().term_text(app.input.as_ref()).to_string())
       .style(match app.input_mode {
            InputMode::Normal => Style::default(),
            InputMode::Editing => Style::default().fg(Color::Yellow),
        })
        .block(Block::default().borders(Borders::ALL).title("Input"));
    f.render_widget(input, chunks[2]);
```

Please this is my first time working with rust would there be any way to work this ?

**Comment by Canop** [comment]
I have no idea what that `render_widget` and `Paragraph` are. Are they designed to take in input a string with TTY escape sequences ? I guess no.

**Comment by ahmedsaheed** [comment]
The `render_widget` and `paragraphs ` are modules from `tui` as shown [here](https://docs.rs/tui/0.11.0/tui/widgets/index.html). I am not quite sure if those modules are designed to to take in input a string with TTY escape sequences.  The `paragraph` is mainly used to display the text. while the `render_widget` displays it to screen.
