### ISSUE TITLE
Pass InputField into a MadSkin

### ISSUE THREAD

**Issue by ahmedsaheed** [Canop/termimad#33]
GIven  an input field
```rs  
 Input: InputField::default(),
```

How do i get the input rendered as MD with a skin like so ?

```rs  
skin.write_in_area_on(w, Input, &self.area);
```

I am just trying to render MD directly from the input

**Comment by Canop** [comment]
You mean you want to render in another area the text the user typed in the input ?

**Comment by ahmedsaheed** [comment]
Exactly, what i am trying to do is render the user input as markdown on a seperate area. It's kind of tricky for me to achieve.

**Comment by ahmedsaheed** [comment]
okay, thanks a million

**Comment by Canop** [comment]
I've added this example: https://github.com/Canop/termimad/tree/master/examples/render-input-markdown

If you have more questions, you might also ask in the chat room: https://miaou.dystroy.org/3768
