### ISSUE TITLE
Indented list rendering

### ISSUE THREAD

**Issue by schpet** [Canop/termimad#41]
i'm seeing some surprising rendering for indented lists, given this input

```rs
fn main() {
    let doc = r#"
list one:

- a
    - b
        - c
            - d

list two:

- a
  - b
    - c
      - d
"#;
    termimad::print_text(doc);
}
```

i see a dark background and the list indentation doesn't seem quite right:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/921605/219481855-91c8c32c-99ef-4770-9845-c0ab9b699c64.png">

i'd expect output more like glow's:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/921605/219482167-a1754263-7730-4efd-9b35-76681a2cbfa3.png">

wanted to confirm this is a bug before trying to take a stab at a PR. i'm a rust noob so not confident i'd be able to fix it, but maybe 🤞🏻 .

**Comment by Canop** [comment]
Not an implementation bug but a shortcoming of my requirements: I didn't even consider supporting list depth. So when you add 4 spaces, you just get some code block.

I'll have a look at how I could support this.

**Comment by schpet** [comment]
@Canop ah! that explains the background. appreciate you checking this out!

**Comment by Canop** [comment]
To ensure compatibility, I'll only handle the 3 first levels. After that it will still be considered as code.

**Comment by Canop** [comment]
@schpet Thanks for letting me know. But I'll do it anyway because it looks the right thing to do.
