### ISSUE TITLE
How to render markdown dynamically in real time

### ISSUE THREAD

**Issue by gngpp** [Canop/termimad#42]
Code text similar to the stream returned by CHATGPT is rendered dynamically as a complement
<img width="1145" alt="image" src="https://github.com/Canop/termimad/assets/51810656/845f7718-0cb8-435d-8361-ddcf8e8f70ad">

The actual rendering looks like this:

<img width="1113" alt="image" src="https://github.com/Canop/termimad/assets/51810656/fbddf484-3a6d-4aaa-a132-6306727bf4a4">

**Comment by ifsheldon** [comment]
+1. I also wonder how this can be implemented. My current idea to work around this is to print raw strings and store these chunks, then once the completion is finished, clear the previous output and render the full content in md using termimad.

**Comment by Canop** [comment]
Why wait for the end ? If you receive those chunks in an application, you can render them like in this example: https://github.com/Canop/termimad/tree/main/examples/render-input-markdown

**Comment by Canop** [comment]
A word of caution: termimad isn't a universal renderer (there's not even any support for images). Its main use cases are for building terminal applications and it may not be suited to render what chatgpt outputs (no idea here).

**Comment by ifsheldon** [comment]
OK, I'm looking into it and will try to make a PR to add a simpler example.

**Comment by gngpp** [comment]
OK

**Comment by ifsheldon** [comment]
I think this is the minimum code to do this
```rust
use std::io::{stdout, Write};
use std::thread::sleep;
use termimad::crossterm::{cursor, ExecutableCommand};
use termimad::{FmtText, MadSkin};

const MARKDOWN_TEXT: &str = r#"
# Hello

This is inline code `print("hello")`.

// wrap below to show code block
print("hello")


Here ends it.
"#;


fn main() {
    let skin = MadSkin::default();
    stdout().execute(cursor::Hide).unwrap();
    let mut string_buffer = String::new();
    for (i, chunk) in MARKDOWN_TEXT.chars().enumerate() {
        stdout().execute(cursor::SavePosition).unwrap();
        string_buffer.push(chunk);
        let formatted_text = FmtText::from(&skin, &string_buffer, None); // can have Some(width) to enable hard wrapping
        print!("{}", formatted_text);
        stdout().flush().unwrap();
        let is_last_one = i == MARKDOWN_TEXT.len() - 1;
        if !is_last_one {
            stdout().execute(cursor::RestorePosition).unwrap();
        }
        sleep(std::time::Duration::from_millis(100));
    }
    stdout().execute(cursor::Show).unwrap();
    sleep(std::time::Duration::from_millis(500));
}
```

I got the idea from https://github.com/Canop/termimad/blob/c3f75b6d71a798fc6ff5b6d2f7445aad4568bb07/examples/render-input-markdown/view.rs#L96
and 
https://github.com/Canop/termimad/blob/c3f75b6d71a798fc6ff5b6d2f7445aad4568bb07/examples/render-input-markdown/view.rs#L98

These two line essentially do the same, which is rendering over and over again rather than incrementally rendering texts.
