### ISSUE TITLE
Display fenced code block issue

### ISSUE THREAD

**Issue by ifsheldon** [Canop/termimad#45]
Hi! When I try to test printing code blocks, I found that the printing has a small issue.

My code is 

<img width="419" alt="image" src="https://github.com/Canop/termimad/assets/39153080/abd7e52e-ce12-46e6-80aa-4593c192f825">

Then I got this

<img width="315" alt="image" src="https://github.com/Canop/termimad/assets/39153080/b4c31678-05f3-4c58-88ae-586438f06901">

You see `python` is printed out. I see #1 is not implemented so syntax highlighting is not working, but I think as least termimad should omit the language name.

**Comment by Canop** [comment]
You're right. It's a bug.

**Comment by Canop** [comment]
The "python" string should be removed, I'll look for that, but you're misusing the lib.
Notice how you also have the  `#` instead of a proper title.
You should use `print_text`, which supports line types, and not `print_inline` which is dedicated to small "inline" strings.

**Comment by ifsheldon** [comment]
OK, sorry about that. Closing this now.

**Comment by Canop** [comment]
> sorry about that

No worry, this happens. I'll try to make the doc clearer.
