### ISSUE TITLE
Code blocks are 100 columns even if `Some(< 100)` is passed to `text`

### ISSUE THREAD

**Issue by noncombatant** [Canop/termimad#50]
`termimad` is a great help to me, so thanks for building it!

I am doing this:

```rust
fn text_width() -> usize {
    let (terminal_width, _) = terminal_size();
    let terminal_width = terminal_width as usize;
    match env::var("MANWIDTH") {
        Ok(man_width) => match man_width.parse::<usize>() {
            Ok(w) => min(terminal_width, w),
            Err(_) => min(terminal_width, 80_usize),
        },
        Err(_) => min(terminal_width, 80_usize),
    }
}

fn terminal_text<'a>(s: &'a str, stream: Stream, skin: &'a MadSkin) -> TerminalText<'a> {
    if atty::is(stream) {
        TerminalText::Formatted(skin.text(s, Some(text_width())))
    } else {
        TerminalText::String(s)
    }
}
```

I find that even when the requested or real width is < 100, the inverted style for code blocks is 100 columns wide. The code in the block still wraps at the requested width. But it ends up noodling up the formatting when the terminal is < 100 wide.

Thanks!

**Comment by noncombatant** [comment]
Clarification: This only seems to happen if the code block needed to be wrapped when limited to `text_width()` columns. If no wrapping was necessary, the code block is not extended to 100 columns. Hope this helps.

**Comment by Canop** [comment]
`TerminalText` isn't a Termimad thing. Can you please write a reproducible example using only Termimad features ?
