### ISSUE TITLE
"coloor" dependency introduces LGPL-3.0

### ISSUE THREAD

**Issue by matthiasbeyer** [Canop/termimad#51]
First of all: **I am not a lawyer**.

With that out of the way: The `coloor` dependency depends (since its 0.6.0 release) on a crate that is LGPL-3.0.

To my understanding, that means that the `coloor` crate is LGPL-3.0 itself, because of static linking and LGPL is only "lesser" for non-static linking, is it not? That would mean that termimad is LGPL-3.0 since the introduction of the `coloor` dependency as well.

I found that because CI broke here: https://github.com/TheNeikos/type_description/pull/265 ([job](https://github.com/TheNeikos/type_description/actions/runs/6693913348/job/18186205379)).

**Comment by Canop** [comment]
Damn. And I had scrapped my alternate implementation of the function I use in ansi_colours, just to make one thing less to maintain, I don't think I even kept the branch...

I'll remove the ansi_colours dependency when I can, but if you (or somebody else) finds or write (either separately) or in coolor the necessary function, it would help me.

**Comment by matthiasbeyer** [comment]
You seem not to use any github actions, why is that? I just wanted to add a `cargo-deny` job, which would have found the issue before it was introduced,... but found that there are no actions at all and wondered why that is?

**Comment by Canop** [comment]
I use some of them, sometimes, depending on the project. But I removed most of them because they're so slow and because they mostly catch problems I'd rather catch locally instead of pushing commits for that (I'm the author of almost all the commits on my projects).

A GH action catching licence problems looks useful, though. I'd probably accept a PR for that.

**Comment by Canop** [comment]
coolor 0.8 removes the dependency to ansi_colours: https://github.com/Canop/coolor/commit/4fb511640a9c71765ddd5d125b7c5866f8935883
