### ISSUE TITLE
No bug in `crossterm`?

### ISSUE THREAD

**Issue by dpc** [Canop/termimad#6]
I was chasing a bug in `cargo crev verify -1` - the display would be blinking / wrong. Eventually I've found:

```
/// Return a (width, height) with the dimensions of the available
/// terminal in characters.
pub fn terminal_size() -> (u16, u16) {
    let (w, h) = Terminal::new().terminal_size();
    // there's a bug in crossterm 0.9.6. It reports a size smaller by
    //  one in both directions
    (w + 1, h + 1)
}
```

I don't think that's the case, at least on my system (Linux). After I got rid of this additional `+1`s the problem is gone.

**Comment by Canop** [comment]
I'll dive back into this as soon as possible. In the meantime please note that this is dependent of the crossterm subcrate version: crossterm removed then put the offset back.

**Comment by dpc** [comment]
I've pushed a lot of changes to your code in `cargo-crev` BTW. FYi. Don't get too upset. :D

**Comment by Canop** [comment]
Termimad moved to crossterm 0.10
