### ISSUE TITLE
How do I disable tables in Madskin?

### ISSUE THREAD

**Issue by sevenuz** [Canop/termimad#61]
I do not want to print tables in certain cases but want to use normal |hier|there|
How can I reset the style of tables?

**Comment by Canop** [comment]
You want an option to hide tables ?

**Comment by Canop** [comment]
I'm sorry but I still miss your intent. Do you want to print the raw markdown, not interpreted ? What's "normal output" ? Is your question about wrapping ?

**Comment by sevenuz** [comment]
Yes, so that tables are printed as normal ascii. With the option limit_to_ascii(), the tables use normal | but the indention and color still changes. Alternatively, how do I print normal output in a scroll view? With print!() it changed the indention and line breaks. Thank You for the quick reply!

**Comment by Canop** [comment]
Actually, a text-view for basic text, without markdown interpretation, would be quite easy to add to termimad and would be consistent, but I never needed it so I didn't build it.

**Comment by sevenuz** [comment]
That would be nice, I also found 
```
    // another one: see that the arguments aren't interpreted as markdown,
    //  which is convenient for user supplied texts
    mad_print_inline!(&skin, "**$0:** ` area = $2 ` and ` perimeter = $1 `", "Disk", "2*π*r", "π*r²");
```
in the inline-template example. How would I use it in a scrollview?

**Comment by sevenuz** [comment]
My workaround now is, that I put a blank space in front of the table. This avoids the rendering. 

But now I have another problem. From an indentation of 3, the scrollview starts a new line. Why?

**Comment by sevenuz** [comment]
Okey, my workaround for that is
```
‎‎format!( "{:indent$} {}", "‎<200e>", text, indent = 3); ‎ ‎ 
```
The left-to-right mark (LRM) is a [control character](https://en.wikipedia.org/wiki/Control_character) (an invisible formatting character).

Kind of a hack but it works :D
