### ISSUE TITLE
MadSkin.print_text() Can Panic on Broken Pipe!

### ISSUE THREAD

**Issue by zicklag** [Canop/termimad#7]
Hey there, thanks for this awesome library. I'm using it for my organization's new [Lucky](https://github.com/katharostech/lucky) project.

Would it be possible to have a version of `MadSkin.print_text` that returns a result instead of panicking? I would much prefer to print a proper error message than to panic.

**Comment by Canop** [comment]
`print_text` only does a `print!` of the formatted text.

The `print!` macro isn't designed to handle IO errors (this is probably relevant: https://github.com/rust-lang/rust/issues/46016).

There are a few functions in Termimad already using write and raising errors but none has the convenience  of `print_text`. I'll add a new one.

**Comment by Canop** [comment]
@zicklag  can you please confirm that your problem is indeed solved by the new functions added in Termimad 0.7.3 ?

**Comment by zicklag** [comment]
That worked perfect, thanks!

I think Termimad will help add a lot of polish to my CLI's help pages. :slightly_smiling_face:

**Comment by Canop** [comment]
@zicklag I'd like a few screenshots for my gallery when it's finished, if it's possible.

**Comment by zicklag** [comment]
Sure thing. I'd be glad to.
