### ISSUE TITLE
Executable

### ISSUE THREAD

**Issue by sombrastudios** [Canop/termimad#9]
Is there a simple way to use this as an executable?

One workflow I'd like to have is the following:

Having open a text editor to edit markdown
and termimad in another window, outputting the formatted markdown and watching for file changes (in order to update the markdown, whenever I hit safe

**Comment by Canop** [comment]
There's the [clima](https://github.com/Canop/clima) executable. It could be combined with watch, inotifywait, entr, or another similar utility.

I probably should update clima, though, it's a little behind in termimad versions.

**Comment by sombrastudios** [comment]
Thanks for the quick and helpful answer

**Comment by Canop** [comment]
@sombrastudios  I just released a new version of Clima.

It now has a `--print` option so that Clima can be used to just print to stdout (i.e. not open the scrollable viewer).

**Comment by sombrastudios** [comment]
Just tested it out, works like a charm.
Thank you!
